### PR TITLE
Fixed the problem and made the comparison of the w/ cross-product

### PR DESCRIPTION
**Pull request by jiazou-bigdata**
and w/o cross product fair. Now the implementations are exactly consistent.
We still observed the significant performance gain similar to what we have observed before.

On xgboost with 500 trees:

w/o cross product: 
-- latency: 25.3478 seconds
-- results: output count:2200000. positive count:1561484

w/ cross product: 
-- latency: 11.5955 seconds
-- results: total count:2200000  positive count:1561484

How to replicate the results:  See [here](https://github.com/asu-cactus/netsdb/pull/62)

### CODE REVIEW

**Comment by jiazou-bigdata** [comment]
@hguan6 I think I've fixed the problem. Please take a look.

**Comment by hguan6** [comment]
> @hguan6 I think I've fixed the problem. Please take a look.

I don't understand when the `void postprocessing()` function in TreeResult.h is called.

**Comment by jiazou-bigdata** [comment]
> > @hguan6 I think I've fixed the problem. Please take a look.
> 
> I don't understand when the `void postprocessing()` function in TreeResult.h is called.

Sorry I may forgot to commit a file that is newly added. I will commit it immediately once I arrive at home. Now I can only access my mobile phone at my son’s flute class…

**Comment by jiazou-bigdata** [comment]
> > @hguan6 I think I've fixed the problem. Please take a look.
> 
> I don't understand when the `void postprocessing()` function in TreeResult.h is called.

@hguan6 I have added this file back: 

https://github.com/asu-cactus/netsdb/blob/high-performance-cross-product/src/builtInPDBObjects/headers/TreeResultPostProcessing.h

Please try again and let me know if any questions. Again, I apologize for the inconvenience.

**Comment by hguan6** [comment]
> > > @hguan6 I think I've fixed the problem. Please take a look.
> > 
> > 
> > I don't understand when the `void postprocessing()` function in TreeResult.h is called.
> 
> @hguan6 I have added this file back:
> 
> https://github.com/asu-cactus/netsdb/blob/high-performance-cross-product/src/builtInPDBObjects/headers/TreeResultPostProcessing.h
> 
> Please try again and let me know if any questions. Again, I apologize for the inconvenience.

I successfully ran w/ cross product, but came across some problems w/o cross product.

w/ cross product, I got 
total count:2200000
positive count:1562608

**Comment by hguan6** [comment]
> e added this

I can successfully run the code but I got different results for both w/ and w/o cross product.
output count:2200000
positive count:1562608

**Comment by jiazou-bigdata** [comment]
@hguan6 That is possibly because of the test file that we used are slightly different. It makes sense because each time we generate the test data, it uses a random split. Correct?

I suggest you should focus on:
1.  Are these two versions have consistent results?
2. Is the optimized version is faster? How much faster?
3. Any problems you observed?

**Comment by hguan6** [comment]
@jiazou-bigdata I am using the lab ubuntu to run the experiments. With cross inference, the model inference time is 8.8s. W/o cross inference, I got 
****UDF Execution Time Duration: ****11.2653 secs.
****UDF Load Model Time Duration: ****0.255766 secs.
Does UDF execution time duration equal to model inference time?

I was using the same HIGGS test dataset in the `experiment` folder, so we used different test sets.

**Comment by hguan6** [comment]
@jiazou-bigdata I actually used the HIGGS test set in the s3 bucket, which may be different from yours.

**Comment by jiazou-bigdata** [comment]
> @jiazou-bigdata I am using the lab ubuntu to run the experiments. With cross product, the model inference time is 8.8s. W/o cross product, I got ****UDF Execution Time Duration: ****11.2653 secs. ****UDF Load Model Time Duration: ****0.255766 secs. 

Which platform did you use?

> Does UDF execution time duration equal to model inference time?
Yes.

> I was using the same HIGGS test dataset in the `experiments` folder, so we used different test sets.
Do you mean you are using a HIGGS test dataset in the `experiments` folder on the physical linux server? I am using AWS r4.2xlarge instance and I create the testing data on that machine.

**Comment by hguan6** [comment]
> Which platform did you use?

The lab ubuntu has a "Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz". The memory size is 62.5G. I can rerun it on the AWS r4.2xlarge instance to verify.


> Do you mean you are using a HIGGS test dataset in the `experiments` folder on the physical linux server? I am using AWS r4.2xlarge instance and I created the testing data on that machine.

I used the HIGGS test dataset in the AWS s3 bucket, which may be different from yours.

**Comment by jiazou-bigdata** [comment]
@hguan6 

Thanks!

Another thing is that I used 15GB memory for buffer pool on r4.2xlarge. You can also try to start the server using larger memory:

./scripts/startPseudoCluster.py 8 15000

**Comment by hguan6** [comment]
@jiazou-bigdata Okay, thank you! Let me do it now.

**Comment by hguan6** [comment]
Here are the results from AWS r4.2xlarge instance:

w/o cross product:
-- latency: 26.1514 seconds
-- results: output count:2200000. positive count:1562608

w/ cross product:
-- latency: 14.8412 seconds
-- results: total count:2200000 positive count:1562608

Again, I used the Higgs test set in the AWS s3 bucket.

**Pull request merged**
