### PR TITLE
add support for criteo

### PR DESCRIPTION
**Pull request by hguan6**

### CODE REVIEW

**Comment by jiazou-bigdata** [comment]
@hguan6 

Met an error when running this command: python data_processing.py -d criteo -n 10000000

tar: /home/ubuntu/netsdb/model-inference/decisionTree/experiments/dataset: Not found in archive
tar: Exiting with failure status due to previous errors

Any suggestions?

**Comment by hguan6** [comment]
> @hguan6
> 
> Met an error when running this command: python data_processing.py -d criteo -n 10000000
> 
> tar: /home/ubuntu/netsdb/model-inference/decisionTree/experiments/dataset: Not found in archive tar: Exiting with failure status due to previous errors
> 
> Any suggestions?

Sorry, the data processing script has not been fully tested. I manually downloaded the dataset and extract a portion of them to train a model. Will make it work soon. 
Now the training and testing scripts work well.

**Comment by hguan6** [comment]
> @hguan6
> 
> Met an error when running this command: python data_processing.py -d criteo -n 10000000
> 
> tar: /home/ubuntu/netsdb/model-inference/decisionTree/experiments/dataset: Not found in archive tar: Exiting with failure status due to previous errors
> 
> Any suggestions?

Now the data_processing.py script should work. Note that the "-n" argument is not implemented in the current version. 

I have a question concerning git commit. During development, I made many commits in order to push the changes to GitHub so that I can use the updated code in the agave environment. Shall I save the updated codes somewhere else, and delete the old branch and this old pull request, and then create a new branch and new PR?

**Comment by hguan6** [comment]
This pull request has been merged to 41-decisiontree-gpu.

**Pull request closed without merging**
