### PR TITLE
41 decisiontree gpu

### PR DESCRIPTION
**Pull request by mahidhar96**
This version supports GPU benchmarking of
HummingbirdPytorchGPU
HummingbirdTorchScriptGPU
ONNXGPU

for:
xgboost
randomforests

TO DO
1. TVMGPU must be built from source
2. some rapids ai, CuML requirements are conflicting with the existing requirements

### CODE REVIEW

**Comment by jiazou-bigdata** [comment]
Great, Mahidhar!

Can you create an image of your AWS instance, which we can use to help test and review your work?

**Comment by jiazou-bigdata** [comment]
@mahidhar96 

FYI... I've created an AMI image from your instance named decision-forest-bench-GPU.
If possible, let's discuss this later this afternoon.

**Comment by jiazou-bigdata** [comment]
@mahidhar96 
I've met some errors at the end of the execution, where are these errors from?

(rapids-22.08) ubuntu@ip-172-31-24-156:~/netsdb/model-inference/decisionTree/experiments$ python test_model.py -d higgs -m xgboost -f NvidiaFILGPU



==============EXPERIMENT STARTING=========================
DATASET: higgs
MODEL: xgboost
FRAMEWORK: NvidiaFILGPU
Query Size: 100000
Batch Size: 100000
Trees 1600
Depth 8
Time Taken to load higgs as a dataframe is: 5554.696083068848
[08:14:09] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1660208897656/work/src/learner.cc:627: 
Parameters: { "verbose" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


Time Taken to load sklearn model: 423.63667488098145
Time Taken to predict on NvidiaFILGPU is 1438.4582042694092
Time Taken to write results to a text file for NvidiaFILGPU is 572.899580001831
Classification Report NvidiaFILGPU
              precision    recall  f1-score   support

           0       0.85      0.59      0.70   1034836
           1       0.71      0.91      0.80   1165164

    accuracy                           0.76   2200000
   macro avg       0.78      0.75      0.75   2200000
weighted avg       0.78      0.76      0.75   2200000

################
Time Taken to convert NvidiaFILGPU model: 5861.56439781189
TOTAL Time Taken for NvidiaFILGPU: 7873.032569885254
==============EXPERIMENT ENDING=========================

Traceback (most recent call last):
  File "fil.pyx", line 273, in cuml.fil.fil.ForestInference_impl.get_dtype
AttributeError: 'NoneType' object has no attribute 'float32'
Exception ignored in: 'cuml.fil.fil.ForestInference_impl.__dealloc__'
Traceback (most recent call last):
  File "fil.pyx", line 273, in cuml.fil.fil.ForestInference_impl.get_dtype
AttributeError: 'NoneType' object has no attribute 'float32'

**Comment by mahidhar96** [comment]
I'm not sure where these are coming from. I'm still investigating these errors. I thought it might be at the end of loading the model, where there is no data, but FIL is trying to stream it and convert it to float32 (because it doesn't support float64). I'm going through their code to investigate this. 

 

[https://github.com/rapidsai/cuml/blob/branch-22.10/python/cuml/fil/fil.pyx](https://github.com/rapidsai/cuml/blob/branch-22.10/python/cuml/fil/fil.pyx) This is the file that error is referring to, but I didn't find anything it is not called float32 on that particular line. get_dtype function is on line 277, and it is accessing float32 from numpy, but it should do this every time it imports numpy, but it is only at that line. I'm still investigating this.

**Comment by nwstephens** [comment]
I got this message from @jiazou-bigdata 

I just tried rapids-22.10 using the below installation. 

```
conda create -n rapids-22.10 -c rapidsai-nightly -c nvidia -c conda-forge \
rapids=22.10 python=3.9 cudatoolkit=11.5
```

However, the error showed up again at the very end, probably when the model object gets freed. 

Traceback (most recent call last):

```
File "fil.pyx", line 282, in cuml.fil.fil.ForestInference_impl.get_dtype
AttributeError: 'NoneType' object has no attribute 'float32'
Exception ignored in: 'cuml.fil.fil.ForestInference_impl.__dealloc__'
Traceback (most recent call last):
File "fil.pyx", line 282, in cuml.fil.fil.ForestInference_impl.get_dtype
AttributeError: 'NoneType' object has no attribute 'float32'
```

**Comment by jiazou-bigdata** [comment]
> I got this message from @jiazou-bigdata
> 
> I just tried rapids-22.10 using the below installation.
> 
> ```
> conda create -n rapids-22.10 -c rapidsai-nightly -c nvidia -c conda-forge \
> rapids=22.10 python=3.9 cudatoolkit=11.5
> ```
> 
> However, the error showed up again at the very end, probably when the model object gets freed.
> 
> Traceback (most recent call last):
> 
> ```
> File "fil.pyx", line 282, in cuml.fil.fil.ForestInference_impl.get_dtype
> AttributeError: 'NoneType' object has no attribute 'float32'
> Exception ignored in: 'cuml.fil.fil.ForestInference_impl.__dealloc__'
> Traceback (most recent call last):
> File "fil.pyx", line 282, in cuml.fil.fil.ForestInference_impl.get_dtype
> AttributeError: 'NoneType' object has no attribute 'float32'
> ```

@nwstephens Thanks Nathan for getting back to us. Any suggestions?

**Review by hguan6 — APPROVED** [review]
I tested the code and think that it is ready to be merged to the master branch.

**Pull request merged**
