### PR TITLE
High performance cross product

### PR DESCRIPTION
**Pull request by jiazou-bigdata**
Added support for the RandomForest model w/ and w/o CrossProduct optimization. The CrossProduct optimization achieved more than 2x speedup.

Note that the following Compiler flags are used and may need to be tuned for different environment: 

src/conf/headers/Configuration.h:

```
#ifndef DEFAULT_MEM_SIZE
#define DEFAULT_MEM_SIZE ((size_t)(62) * (size_t)(1024) * (size_t)(1024))
#endif

#ifndef DEFAULT_NUM_CORES
#define DEFAULT_NUM_CORES 8 
#endif
```

./src/builtInPDBObjects/headers/TreeResult.h:

`#define MAX_BLOCK_SIZE 275000`

./src/builtInPDBObjects/headers/Forest.h:

`#define MAX_NUM_TREES 1600
#define MAX_NUM_NODES_PER_TREE 512`

### **w/o CrossProduct optimization:**

```
./scripts/cleanupNode.sh

./scripts/startPseudoCluster.py 8 15000

bin/testDecisionForest Y 2200000 28 275000 F A 32 model-inference/decisionTree/experiments/HIGGS.csv_test.csv

bin/testDecisionForest N 2200000 28 275000 F A 32 model-inference/decisionTree/experiments/HIGGS.csv_test.csv model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb RandomForest
```

**output count:2200000
positive count:1119844**

_1st time execution:_

****UDF Execution Time Duration: ****112.956 secs.
****UDF Load Model Time Duration: ****4.20368 secs.

_2nd time execution:_

****UDF Execution Time Duration: ****107.671 secs.
****UDF Load Model Time Duration: ****0.804746 secs.

### **w/ CrossProduct optimization:**

```
./scripts/cleanupNode.sh 

./scripts/startPseudoCluster.py 8 15000

bin/testDecisionForestWithCrossProduct Y 2200000 28 275000 32 model-inference/decisionTree/experiments/HIGGS.csv_test.csv model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb RandomForest

//**Note that now we need provide one more parameter at the end: numTrees**

bin/testDecisionForestWithCrossProduct N 2200000 28 275000 32 model-inference/decisionTree/experiments/HIGGS.csv_test.csv model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb RandomForest **1600**
```

**total count:2200000
positive count:1119844**

_1st execution time:_

****Model Inference Time Duration: ****45.7068 secs.

_2nd execution time:_

****Model Inference Time Duration: ****44.1866 secs.

### CODE REVIEW

**Comment by jiazou-bigdata** [comment]
@hguan6 Please take a look. Let me know if any problem.

**Comment by hguan6** [comment]
After I ran `bin/testDecisionForest N 2200000 28 275000 F A 32 HIGGS.csv_test.csv model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb RandomForest`, I got an error:
```
not builtin and no catalog connection, typeId for pdb::AbstractAggregateCompis 8191
not builtin and no catalog connection, typeId for pdb::Computationis 8191
Not create a set and not load new data to the input set
to search for set in Catalog: decisionForest:labels
Cannot remove set from Catalog, Set decisionForest.labels does not exist 
to broadcast StorageRemoveUserSet
2:getNextObject with msgSize=80
Failed to delete set on 1 nodes. Skipping registering with catalog
to search for set in Catalog: decisionForest:labels
Set decisionForest:labels does not exist
the internalTypeName for pdb::Vector<float> is pdb::Vector<pdb::Nothing> and typeID is 159
Create PDBCatalogSet instance of primary key being: decisionForest:labels
the internalTypeName for pdb::Vector<float> is pdb::Vector<pdb::Nothing> and typeID is 159
Create PDBCatalogSet instance of primary key being: decisionForest:labels
This is not Manager Catalog Node, thus metadata was only registered locally!
Node IP: localhost updated correctly!
******************** desired size = 1000********************
%%%%%%%%%%%%%%%%%DistributedStorageManagerServer: to add private set%%%%%%%%%%%%%%%
Page size is determined to be 67108864
No Computation and Lambda for partitioning
to broadcast StorageAddset
received StorageAddSet
%%%%%%%%Pangea to add a private set%%%%%%%%%%%
creating set in Pangea in distributed environment...with setName=labels
to add set with dbName=decisionForest, typeName=pdb::Vector<float>, setName=labels, setId=1, pageSize=67108864
type not recognized: -1
type doesn't  exist for name=pdb::Vector<float>, and we store it as default type
path to meta file is pdbRoot_localhost_8109/meta/1_decisionForest/0_UnknownUserData/1_labels
file opened:pdbRoot_localhost_8109/data/1_decisionForest/0_UnknownUserData/1_labels
meta file exists
Number of existing pages = 0
to add set with dbName=decisionForest, typeName=UnknownUserData, setName=labels, setId=1, pageSize=67108864
2:getNextObject with msgSize=52
broadcasted StorageAddSet
Created set.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

**Comment by jiazou-bigdata** [comment]
Hi Hong, I will investigate the error this evening after teaching and meetings. It seems the program meets errors when parsing the model. Have you tried to use the model that I uploaded to S3 for converting to netsDB?

**Comment by hguan6** [comment]
> Hi Hong, I will investigate the error this evening after teaching and meetings. It seems the program meets errors when parsing the model. Have you tried to use the model that I uploaded to S3 for converting to netsDB?

Yes, I converted it from the .pkl file in S3.

**Comment by jiazou-bigdata** [comment]
@hguan6 I fixed the problem. Please check again.

Note that for the second command, now we need add a parameter to specify the number of trees at the end.

bin/testDecisionForestWithCrossProduct N 2200000 28 275000 32 model-inference/decisionTree/experiments/HIGGS.csv_test.csv model-inference/decisionTree/experiments/models1/higgs_randomforest_1600_8_netsdb RandomForest 1600

**Comment by hguan6** [comment]
@jiazou-bigdata I still got the same error message. Do I need to do something else besides pulling the latest code?

**Comment by jiazou-bigdata** [comment]
> @jiazou-bigdata I still got the same error message. Do I need to do something else besides pulling the latest code?
The model files downloaded from S3 run well from my side. Which branch are you at? Did you recompile the code by running scons libDFTest?

**Comment by hguan6** [comment]
> The model files downloaded from S3 run well from my side. Which branch are you at? Did you recompile the code by running scons libDFTest?

I didn't recompile the code. Let me do that now.

**Comment by hguan6** [comment]
I recompiled the code. The w Cross product code runs well, and I got:
`****Model Inference Time Duration: ****44.7118 secs.`

But I got some other errors when I ran the code without Cross product. The error message for `bin/testDecisionForest N 2200000 28 275000 F A 32 HIGGS.csv_test.csv model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb RandomForest`:
```
not builtin and no catalog connection, typeId for pdb::AbstractAggregateCompis 8191
not builtin and no catalog connection, typeId for pdb::Computationis 8191
Not create a set and not load new data to the input set
to search for set in Catalog: decisionForest:labels
Cannot remove set from Catalog, Set decisionForest.labels does not exist 
to broadcast StorageRemoveUserSet
2:getNextObject with msgSize=80
Failed to delete set on 1 nodes. Skipping registering with catalog
to search for set in Catalog: decisionForest:labels
Set decisionForest:labels does not exist
the internalTypeName for pdb::Vector<float> is pdb::Vector<pdb::Nothing> and typeID is 159
Create PDBCatalogSet instance of primary key being: decisionForest:labels
the internalTypeName for pdb::Vector<float> is pdb::Vector<pdb::Nothing> and typeID is 159
Create PDBCatalogSet instance of primary key being: decisionForest:labels
This is not Manager Catalog Node, thus metadata was only registered locally!
Node IP: localhost updated correctly!
******************** desired size = 1000********************
%%%%%%%%%%%%%%%%%DistributedStorageManagerServer: to add private set%%%%%%%%%%%%%%%
Page size is determined to be 67108864
No Computation and Lambda for partitioning
to broadcast StorageAddset
received StorageAddSet
%%%%%%%%Pangea to add a private set%%%%%%%%%%%
creating set in Pangea in distributed environment...with setName=labels
to add set with dbName=decisionForest, typeName=pdb::Vector<float>, setName=labels, setId=1, pageSize=67108864
type not recognized: -1
type doesn't  exist for name=pdb::Vector<float>, and we store it as default type
path to meta file is pdbRoot_localhost_8109/meta/1_decisionForest/0_UnknownUserData/1_labels
file opened:pdbRoot_localhost_8109/data/1_decisionForest/0_UnknownUserData/1_labels
meta file exists
Number of existing pages = 0
to add set with dbName=decisionForest, typeName=UnknownUserData, setName=labels, setId=1, pageSize=67108864
2:getNextObject with msgSize=52
broadcasted StorageAddSet
Created set.
model-inference/decisionTree/experiments/models/higgs_randomforest_1600_8_netsdb/951.txt
process inner nodes
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)
```

**Comment by hguan6** [comment]
> Now it should work. Please try again!

Yes, I will try it now. 


> hguan6, can you take a look at this and help merge these two?

Yes, once I finish the TFDF experiments,  I will take a look.

**Pull request merged**
