### PR TITLE
Exclude two features (time and amount) from fraud dataset

### PR DESCRIPTION
**Pull request by hguan6**
These two features are not used as predictors in Hummingbird. Excluding them makes the number of predictors/features 28. The other minor change is to fix a typo in the output file name.

### CODE REVIEW

**Comment by hguan6** [comment]
The other minor change is to fix a typo in output file name.

**Comment by jiazou-bigdata** [comment]
Thanks Hong! Could you please give a link to the Hummingbird script that has the problem? Also, we do not need to keep everything exactly the same with HummingBird, I think. HummingBird is a great paper, but their experiments are not a standard benchmark. Using all the features in the real-world dataset may be more interesting. What do you think?

**Comment by hguan6** [comment]
The Hummingbird script is here: https://github.com/microsoft/hummingbird/blob/bb87598466744aa5729d8b59e14e938c4871e7fa/benchmarks/datasets.py#L41:~:text=X%20%3D%20df%5B%5Bcol%20for%20col%20in%20df.columns%20if%20col.startswith(%22V%22)%5D%5D

The link below is an description of the Fraud dataset:
https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud#:~:text=Features%20V1%2C%20V2,and%200%20otherwise.

I also found that the number_features in the config.json is set to 28.

**Comment by jiazou-bigdata** [comment]
Hong, 

In config.json, every dataset is set to 28 features, which looks incorrect to me. For example, if you download the airline dataset, it only has 14 features. Let's fix that!

Also, can you explain why to remove amount and time? Again, we do not need to follow what other papers do unless there is a solid reason.

**Comment by jiazou-bigdata** [comment]
Just had a discussion with Hong and agreed on several things:
(1) Some Kaggle studies showed that Amount is a good feature for XGBoost classification on the fraud dataset, and they also kept Time and achieved 98% recall on this skewed dataset: [link](https://www.kaggle.com/code/nileshmahajan25/fraud-detection-with-xgboost-recall-98-6)
(2) We are not sure why HummingBird removed these two features, but we find it followed NVidia's gbm bench: [link](https://github.com/NVIDIA/gbm-bench/blob/master/datasets.py) To keep consistent with the previous benchmarks may be a good idea for verification of our benchmark results.
(3) Now the scripts are only tested for a few benchmark datasets, so the config.json needs to be updated for setting up the correct values for features, query, y_col, categorical_col, etc, for other datasets. We will work on that in the next several days.

**Pull request merged**
