### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by jiazou-bigdata**
We want to integrate the benchmark code implemented for Scikit-learn, HummingBird, ONNX-ML from Jiaqing-1 branch to the master branch.

### CODE REVIEW

**Comment by lixi-zhou** [comment]
Hi, I have some comments:
1. should the data be merged to the repository, also I see there are some pdf files?
  - **graphs**
  - **graphs100**
3. redundant cache files should not be merged to the repository: 
  - **__pycache__**
  - **.ipynb_checkpoints**
 3. should the model files be stored somewhere else?
   - **.onnx**
   - **.pkl**
  4. spark **target** folder

**Comment by jiazou-bigdata** [comment]
@mahidhar96 

Let's have a code review for the folder of decision tree experiments, which has many issues.
Most importantly, we should not repeat the code for each dataset: Higgs, Airline, etc..
This means the SQL used for each dataset should be separated from the inferences.

In addition, while we can keep a few model files in the repository for testing/reproduction purpose, each model should have only one copy. Now a model file rf-100-8-6.pkl have multiple copies in HummingBird, Onnx, Scikitlearn, etc. We should remove redundant copies of these models, and put all distinct models to a common folder shared by HummingBird, Onnx, Scikitlearn, etc..

Let's discuss Monday to better organize this part of work.

**Comment by mahidhar96** [comment]
Sure ma'am,

I'm still going through the previous pull request. I'm not pushing any new
code. It's still on my local machine. I'll only commit it after the review
is done.

Thank you,
Mahidhar

**Comment by jiazou-bigdata** [comment]
@mahidhar96 

Mahidhar, if you want to, you can commit your up-to-date code to the integration branch and we can review these together Monday. That way could be efficient!

**Pull request merged**
